name: Build macOS

on:
  push:
    branches: [ "*" ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build macOS Binary
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o pfsms_darwin .

      - name: Pack to Zip
        run: |
          zip pfsms_mac.zip pfsms_darwin

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pfsms-macOS
          path: pfsms_mac.zip